server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_shop?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    database: 0
    enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**

jwt:
  secret: 8677df7fc3a34e2e86a524a6d58035e3
  expiration: 86400000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shop.online.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 文件上传配置
upload:
  path: D:/upload/
  allowed-types: jpg,jpeg,png,gif
  max-size: 5242880 